site_name: Kim Petersen
site_url: https://blog.bartogh.dk
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

nav:
  - Home: index.md
  - Tests:
    - Tests1: Test/test1.md
    - Tests2: Test/test2.md
  - About:
    - About Me: about/about-me.md
    - Childhood: about/childhood.md