site_name: Kim Petersen
site_url: https://blog.bartogh.dk
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand

  plugins:
    - blog
    - search

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
    - Posts: 
      - blog/posts/hello-world.md
      - blog/posts/heythere.md
      
  - Tests:
    - Tests1: Test/test1.md
    - Tests2: Test/test2.md
  - About:
    - About Me: about/about-me.md
    - Childhood: about/childhood.md